porting to python 3
% sudo pip install scapy-http
Collecting scapy-http
  Downloading scapy-http-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-0eeiw7zq/scapy-http/setup.py", line 8
        print 'Installing the HTTP layer extension into Scapy...',
                                                                ^
    SyntaxError: Missing parentheses in call to 'print'